# myservices/constants.py

class myserv_varriable_list:
    API_USER_ROLE = 'api_user'
    ANDROID_USER_ROLE = 'android_user'
    ADMIN_USER_ROLE = 'admin_user'
    JWT_SECRET_KEY = "8ff09627ca698e84a587ccd3ae005f625ece33b3c999062e62dbf6e70c722323"
    pg_config_DBNAME='postgres'
    pg_config_USER='biro'
    pg_config_PASSWORD='biro'
    # pg_config_HOST='10.98.0.87'
    pg_config_HOST='172.18.0.87'
    pg_config_PORT='5432'
    mongo_config_URI='mongodb://localhost:27017/'
    mongo_config_DB='admin'
    mongo_config_COLLECTION='mpwz_users'
    integrated_app_erp ='erp'
    integrated_app_ngb='ngb'
    notification_type_ngb_ccb='CCB'
    notification_type_ngb_cc4='CC4'
    notification_status_APPROVED='APPROVED'
    notification_status_PENDING='PENDING'
    notification_status_REJECTED='REJECTED'
    notification_status_REASSIGNED='REASSIGNED'    
    notification_type_erp_leave='LEAVE'
    notification_type_erp_tada='TADA'
    notification_type_erp_project='PROJECT'